Zenko 3362 enhance ux account
scality/zenko-ui pull request #101
Opened 2021-04-13 07:37 UTC by theocerutti

![image](https://user-images.githubusercontent.com/44285344/114514621-c3fbe180-9c3b-11eb-9a7b-3d7acec0661e.png)
![image](https://user-images.githubusercontent.com/44285344/114514637-cb22ef80-9c3b-11eb-90ed-9032fa80830b.png)

2021-04-13 07:37 UTC, bert-e commented
# Hello theocerutti,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2021-04-13 07:37 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-04-13 12:23 UTC, Cuervino requested changes
- ZENKO-3183 Account details title to add

Could you please align the new title with the content of the table below? It looks like there is at least 1 px discrepancy.
![image](https://user-images.githubusercontent.com/28654802/114551300-7c894b80-9c63-11eb-9118-11a8e74c6248.png)

- ZENKO-3184 'Created On' Column format to adjust on Account list
Thanks, it's good!

2021-04-13 12:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-04-15 14:57 UTC, nicolas2bert commented on src/react/account/AccountList.jsx
> +        Cell: ({ value }) => <div style={{ textAlign: 'right' }}>{formatSimpleDate(new Date(value))}</div>,
We might want to create a `ui-elements/Utility.js` file and import styled component `textAlign: 'right'` from there for reusability.

2021-04-15 14:57 UTC, nicolas2bert commented on src/react/ui-elements/TableKeyValue.jsx
> +    border-spacing: 0;
unity?

2021-04-19 14:29 UTC, theocerutti commented on src/react/account/AccountList.jsx
> +        Cell: ({ value }) => <div style={{ textAlign: 'right' }}>{formatSimpleDate(new Date(value))}</div>,
done

2021-04-19 14:29 UTC, theocerutti commented on src/react/ui-elements/TableKeyValue.jsx
> +    border-spacing: 0;
done

2021-04-19 17:46 UTC, Cuervino approved these changes
LGTM!

2021-04-19 17:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-04-22 19:10 UTC, terrydervaux approved these changes
LGTM

2021-04-23 08:34 UTC, nicolas2bert approved these changes

2021-04-23 09:34 UTC, theocerutti commented
@bert-e approve

2021-04-23 09:34 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-04-23 09:43 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue ZENKO-3362.

Goodbye theocerutti.

2021-04-23 09:43 UTC, merged