ZENKO-3439 create access key
scality/zenko-ui pull request #135
Opened 2021-04-28 14:18 UTC by nicolas2bert

<img width="1792" alt="Screen Shot 2021-04-28 at 4 17 41 PM" src="https://user-images.githubusercontent.com/7453636/116419357-44763100-a83d-11eb-84fb-a58fb9fddf8e.png">

2021-04-28 14:18 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2021-04-28 14:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-04-28 14:20 UTC, nicolas2bert commented
"Success message" reviewed by @wabernatScality.

2021-04-28 19:50 UTC, terrydervaux reviewed
Please, add the first modal describe in the Jira ticket.

2021-04-28 19:50 UTC, terrydervaux commented on src/react/account/details/SecretKeyModal.jsx
> +            title='Create access key'>
```suggestion
            title='Root user Access Keys creation'>
```

2021-04-28 19:50 UTC, terrydervaux commented on src/react/account/details/SecretKeyModal.jsx
> +                    If you lose this access key, you will have to create a new one. You can do this at any time. <br/>
```suggestion
                    If you lose this secret access key, you will have to create a new one. You can do this at any time. <br/>
```

2021-04-29 01:03 UTC, jonathan-gramain approved these changes

2021-04-29 01:03 UTC, jonathan-gramain commented on src/react/account/details/Properties.jsx
> +                <Button icon={<i className="fas fa-plus" />} size="default" onClick={handleAccessKeyCreate} text='Create access key'/>
maybe capitalize the tooltip: "Create Access Key" (only if consistent with the other tooltips around)

2021-04-29 01:03 UTC, jonathan-gramain commented on src/react/account/details/SecretKeyModal.jsx
> +            title='Create access key'>
same comment about capitalizing

2021-04-29 01:03 UTC, jonathan-gramain commented on src/react/account/details/SecretKeyModal.jsx
> +                    You cannot retrieve this again, so copy it carefully and securely now. <br/>
I'd rather use the impersonal form "This cannot be retrieved again, so copy... a new one will have to be created. It can be done at any time.", but @wabernatScality can chime in!

2021-04-29 01:03 UTC, jonathan-gramain commented on src/react/account/details/SecretKeyModal.jsx
> +                            <T.Key> Account name </T.Key>
ditto regarding capitalization

2021-04-29 09:29 UTC, nicolas2bert commented on src/react/account/details/Properties.jsx
> +                <Button icon={<i className="fas fa-plus" />} size="default" onClick={handleAccessKeyCreate} text='Create access key'/>
We choose: "Root user" "Access key ID" and "Secret Access key"

2021-04-29 10:34 UTC, ilkescality approved these changes
LGTM!

2021-04-29 10:44 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/ZENKO-3439/create-access-key` and the
destination branch `development/1.0`.

Please resolve the conflict on **the feature branch** (`feature/ZENKO-3439/create-access-key`).

```bash
 $ git fetch
 $ git checkout origin/feature/ZENKO-3439/create-access-key
 $ git merge origin/development/1.0
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:feature/ZENKO-3439/create-access-key
```

2021-04-29 10:46 UTC, Cuervino requested changes
![image](https://user-images.githubusercontent.com/28654802/116538780-4517d180-a8e8-11eb-95ac-1122de41e873.png)

![image](https://user-images.githubusercontent.com/28654802/116539233-d7b87080-a8e8-11eb-9ac9-ba292c3be64b.png)

![image](https://user-images.githubusercontent.com/28654802/116539133-b8b9de80-a8e8-11eb-83f4-c703b61ab5a6.png)

2021-04-29 12:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-04-29 13:15 UTC, Cuervino requested changes
![image](https://user-images.githubusercontent.com/28654802/116555136-4bb04400-a8fc-11eb-97c2-e56ce258b213.png)
1. "Root user Access keys"
2. "Root user Access keys"
3. "root Access keys"
4. "Access key ID"
5. "Create Access key"
6. Tootlip too far from the string (and too close to the creation date). Set it closer to the Access key ID string (especially that we know the length of the string)
7. Button too small (27 px instead of 32px high), icon size too small, and the style doesn't seem to be the variant "Delete"
8. Delete button too far on the right, better to make it closer to the other columns

It will prevent having an issue of tooltip under the right column.
![image](https://user-images.githubusercontent.com/28654802/116554686-c593fd80-a8fb-11eb-9f01-29a970702260.png)

![image](https://user-images.githubusercontent.com/28654802/116555884-296af600-a8fd-11eb-8c15-3ec22ac97fa0.png)
9. The font size is too small (it's 12px, should be 14px like other buttons)
10. "Secret Access key"

![image](https://user-images.githubusercontent.com/28654802/116556422-b746e100-a8fd-11eb-9bbb-bf2fd48ba4cf.png)
11. it would be nice that this action would be located at the same place, not dependent on the size of the string

![image](https://user-images.githubusercontent.com/28654802/116559717-02162800-a901-11eb-9a73-aa031d9befa4.png)
12. the button "Delete Account" also looks like not being in the variant "Delete"

2021-04-29 14:24 UTC, nicolas2bert commented
1 2 3 4 5 6 7 done
8: we follow what already existed for button "actions" (edit, delete) in locations' list. We might want to change it everywhere. To be discuss :)
9 10 done
11 Is it ok if we work on this comment later?
12 done

2021-04-29 15:11 UTC, Cuervino approved these changes
> 8: we follow what already existed for button "actions" (edit, delete) in locations' list. We might want to change it everywhere. To be discuss :)
You're right, so let's keep it like that!

> 11 Is it ok if we work on this comment later?
Sure!

Nicely done !

2021-04-29 15:11 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-04-29 15:41 UTC, nicolas2bert commented
@bert-e approve

2021-04-29 15:41 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-04-29 15:42 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue ZENKO-3439.

Goodbye nicolas2bert.

2021-04-29 15:42 UTC, merged