ZENKO-3413: adjust date format for tables
scality/zenko-ui pull request #144
Opened 2021-05-06 08:34 UTC by theocerutti

Date format updated from 
![image](https://user-images.githubusercontent.com/44285344/117266403-857dcf00-ae55-11eb-912b-5dd1af5ae4e7.png)
to
![image](https://user-images.githubusercontent.com/44285344/117266445-8dd60a00-ae55-11eb-9099-8e9a8d66db5d.png)

(only for tables)

Tables updated:
* AccountKeys / Created On
* Bucket Browsing / Created On

2021-05-06 08:34 UTC, bert-e commented
# Hello theocerutti,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2021-05-06 08:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-05-06 09:28 UTC, nicolas2bert reviewed
What about object page's **Modified on** column?

2021-05-06 09:32 UTC, theocerutti commented
> What about object page's Modified on column?

It already has the good format
![image](https://user-images.githubusercontent.com/44285344/117275753-a696ed80-ae5e-11eb-9715-27614c9383b0.png)

2021-05-06 10:02 UTC, nicolas2bert approved these changes

2021-05-07 15:55 UTC, Cuervino requested changes
Looks good!

It was not in the requirement, but could you please make those 2 columns aligned to the right (as they are numerical)?
From the visual point of view, it would mainly change the header position, the content would not move.
![image](https://user-images.githubusercontent.com/28654802/117476666-65d1ce00-af5d-11eb-816a-9943b7b48b66.png)

2021-05-07 15:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @cuervino

2021-05-14 14:36 UTC, nicolas2bert commented on src/react/databrowser/buckets/BucketList.jsx
> +                <div style={{ textAlign: 'right', paddingRight: '16px' }}>
Can you also use the TextAligner component here?

2021-05-18 15:41 UTC, Cuervino approved these changes
LGTM!

2021-05-18 15:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-05-23 13:18 UTC, nicolas2bert approved these changes

2021-05-24 08:46 UTC, theocerutti commented
@bert-e approve

2021-05-24 08:46 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-05-24 08:54 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue ZENKO-3413.

Goodbye theocerutti.

2021-05-24 08:54 UTC, merged