ZKUI -17: Add object lock setting page
scality/zenko-ui pull request #199
Opened 2021-11-05 17:07 UTC by ChengYanJin

2021-11-05 17:07 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2021-11-05 17:07 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-17 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.1.0`


Please check the `Fix Version/s` of ZKUI-17, or the target
branch of this pull request.

2021-11-08 14:52 UTC, JBWatenbergScality commented on src/react/databrowser/buckets/ObjectLockSetting.jsx
> +  );
const isLoading = isObjectLockEnabled

2021-11-08 14:52 UTC, JBWatenbergScality commented on src/react/databrowser/buckets/ObjectLockSetting.jsx
> +          {isObjectLockEnabled && (
isObjectLockEnabled === 'Enabled'

2021-11-08 14:52 UTC, JBWatenbergScality commented on src/react/ui-elements/TableKeyValue2.jsx
> +  justify-content: space-between;
align-items: baseline

2021-11-08 17:16 UTC, JBWatenbergScality approved these changes

2021-11-08 17:17 UTC, ChengYanJin commented
/approve

2021-11-08 17:17 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-17 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.1.0`


Please check the `Fix Version/s` of ZKUI-17, or the target
branch of this pull request.




*The following options are set:* **approve**

2021-11-08 20:30 UTC, ChengYanJin commented
/status

2021-11-08 20:30 UTC, bert-e commented
# Status





*Status report is not available.*






*The following options are set:* **approve**

2021-11-08 20:30 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-17 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.1.0`


Please check the `Fix Version/s` of ZKUI-17, or the target
branch of this pull request.




*The following options are set:* **approve**

2021-11-08 22:01 UTC, nicolas2bert requested changes
Missing component tests.

2021-11-08 22:01 UTC, nicolas2bert commented on src/react/databrowser/buckets/ObjectLockSetting.jsx
> +  const hasError = useSelector(
We should handle potential errors.

2021-11-08 22:01 UTC, nicolas2bert commented on src/react/databrowser/buckets/ObjectLockRetentionSettings.jsx
> +  isDefaultRetentionEnabled: Joi.boolean(),
Let's force the default value of `isDefaultRetentionEnabled` to `false` here.

2021-11-08 22:01 UTC, nicolas2bert commented on src/react/databrowser/buckets/ObjectLockSetting.jsx
> +  const isDefaultRetentionEnabled = bucketInfo?.objectLockConfiguration.Rule
We could define a function that takes bucket info and converts it to a "form" object.
And at the bucket creation, do the opposite takes "form infos" and converts them to bucket info.
Something like this: https://github.com/scality/zenko-ui/blob/development/1.1/src/react/backend/location/utils.js#L58

2021-11-09 01:50 UTC, nicolas2bert commented
Also, it should target development/1.0 branch. :)

2021-11-10 22:06 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-17 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.0.7`

* `1.1.0`


Please check the `Fix Version/s` of ZKUI-17, or the target
branch of this pull request.




*The following options are set:* **approve**

2021-11-15 16:19 UTC, nicolas2bert approved these changes
LGTM, please squash the commits. 
Should @Cuervino try/manual test the feature since new changes have been made?

2021-11-16 12:44 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-17 contains:


* `1.1.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.0.7`

* `1.1.0`


Please check the `Fix Version/s` of ZKUI-17, or the target
branch of this pull request.




*The following options are set:* **approve**

2021-11-17 10:17 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/1.1/feature/ZKUI-17-add-object-lock-setting-page` with contents from `feature/ZKUI-17-add-object-lock-setting-page`
and `development/1.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/1.1/feature/ZKUI-17-add-object-lock-setting-page origin/development/1.1
 $ git merge origin/feature/ZKUI-17-add-object-lock-setting-page
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/1.1/feature/ZKUI-17-add-object-lock-setting-page
```





*The following options are set:* **approve**

2021-11-18 17:41 UTC, ChengYanJin commented
/approve

2021-11-18 17:41 UTC, ChengYanJin commented
/status

2021-11-18 17:41 UTC, bert-e commented
# Status





*Status report is not available.*






*The following options are set:* **approve**

2021-11-18 17:41 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/1.1/feature/ZKUI-17-add-object-lock-setting-page` with contents from `feature/ZKUI-17-add-object-lock-setting-page`
and `development/1.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/1.1/feature/ZKUI-17-add-object-lock-setting-page origin/development/1.1
 $ git merge origin/feature/ZKUI-17-add-object-lock-setting-page
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/1.1/feature/ZKUI-17-add-object-lock-setting-page
```





*The following options are set:* **approve**

2021-11-18 18:02 UTC, ChengYanJin commented
/status

2021-11-18 18:02 UTC, bert-e commented
# Status





*Status report is not available.*






*The following options are set:* **approve**

2021-11-18 18:10 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`

* :heavy_check_mark: `development/1.1`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-11-18 18:10 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`

* :heavy_check_mark: `development/1.1`




Please check the status of the associated issue ZKUI-17.

Goodbye chengyanjin.

2021-11-18 18:10 UTC, merged