Feature/zk UI 72 listing users
scality/zenko-ui pull request #238
Opened 2022-02-10 12:42 UTC by MonPote

2022-02-10 12:42 UTC, bert-e commented
# Hello monpote,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-02-10 12:43 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-72 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.1.4`


Please check the `Fix Version/s` of ZKUI-72, or the target
branch of this pull request.

2022-02-18 18:08 UTC, JBWatenbergScality requested changes

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/IAMProvider.jsx
> +    <IAMContext.Provider value={{ iamClient: IAMClient }}>
```suggestion
  return (
    <IAMContext.Provider value={{ iamClient: IAMClientResult || null }}>
```

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountCreateUser.jsx
> +        queryClient.invalidateQueries('listIAMClient');
A quick search on `listIAMClient` is not raising any matches, we probably want to invalidate `['listIAMUsers', accountName]`

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountCreateUser.jsx
> +      })
In order to handle the error we can just dispatch the existing error actions for now I think 🤔

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountUserAccessKeys.jsx
> +        ) : null}
The user won't know why there is such a waring next to the creation date. I think likely when hovering it we should get an explanation tooltip @Cuervino WDYT ?
Additionally the "warning" computation should be abstracted away so that we can easily replace it with an alert when alerting will be configured. I would take the approach to implement a custom hook `const outdatedAlert = useAccessKeyOutdatedStatus(theWholeAccessKeyObject)` which for now would just check creation time but later on could easily be refactored to alert checking. `outdatedAlert` would be either null either `This access key has been generated more than 300 days ago. Please consider change it.`, text to be validated of course.

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountUserList.jsx
> +        )}
We are missing error and loading cases here

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountUserList.jsx
> +  );
I think it would be better to extract those components outside of the AccountUserList definition, you can define them just on top of this file.

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountUserSecretKeyModal.jsx
> +      queryClient.invalidateQueries('listIAMClientUserAccessKeys');
I don't think this is the right invalidated query

2022-02-18 18:08 UTC, JBWatenbergScality commented on src/react/account/AccountUserAccessKeys.jsx
> +    queryKey: ['listIAMClientUserAccessKeys', IAMUserName],
It likely should be the same query as the one used in the table to share cache keys ([line 56 in src/react/account/AccountUserList.jsx](https://github.com/scality/zenko-ui/pull/238/files#diff-36a1ebb41c89476d16eaee94f9f30a23f5f8f3d0bc7032d1030def24904d4a3aR55-R59) )

2022-02-22 14:15 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-72 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.2.0`


Please check the `Fix Version/s` of ZKUI-72, or the target
branch of this pull request.

2022-02-22 15:47 UTC, JBWatenbergScality approved these changes

2022-02-22 17:06 UTC, MonPote commented
/approve

2022-02-22 17:06 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-72 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.2.0`


Please check the `Fix Version/s` of ZKUI-72, or the target
branch of this pull request.




*The following options are set:* **approve**

2022-02-22 21:08 UTC, ChengYanJin approved these changes

2022-02-22 21:08 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-02-22 21:15 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`



Please check the status of the associated issue ZKUI-72.

Goodbye monpote.

2022-02-22 21:15 UTC, merged