ZKUI-97: Add copy arn button in the user list
scality/zenko-ui pull request #246
Opened 2022-02-24 14:35 UTC by ChengYanJin

2022-02-24 14:35 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-02-24 14:35 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-97 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.2.0`


Please check the `Fix Version/s` of ZKUI-97, or the target
branch of this pull request.

2022-02-24 14:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-02-25 11:41 UTC, JBWatenbergScality requested changes

2022-02-25 11:41 UTC, JBWatenbergScality commented on src/react/ui-elements/CopyARNButton.jsx
> +
The logic seems to be duplicated with the one of the Clipboard component. I vote for a refactoring of the existing component such that:
 - we create a custom hook `useClipboard` defined as :
```
type useClipboard = () => {copy: (text: string) => void, status: 'idle' | 'success' | 'unsupported'} 
``` 
 - we create a generic component with a children props wrapping this children with the tooltip mentioning the success of the copy
 - we change the existing clipboard component to use this generic one
 - we change this implementation with the generic component
-

2022-02-25 11:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jbwatenbergscality

2022-02-27 11:35 UTC, ChengYanJin commented
Hello @Cuervino
 
We suggest removing the **tooltip** "Copied!" which provides the feedback of the copy action.

Instead of this behavior,
We will temporarily change the text of the Copy button to"Copied" with a green tick icon.

WDYT?

2022-02-27 11:35 UTC, ChengYanJin commented
/approve

2022-02-27 11:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jbwatenbergscality







*The following options are set:* **approve**

2022-02-28 16:21 UTC, JBWatenbergScality approved these changes

2022-02-28 16:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **approve**

2022-02-28 16:22 UTC, MonPote approved these changes

2022-02-28 16:22 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-02-28 16:29 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`



Please check the status of the associated issue ZKUI-97.

Goodbye chengyanjin.

2022-02-28 16:29 UTC, merged