Improve table usage
scality/zenko-ui pull request #267
Opened 2022-03-08 16:48 UTC by AsmaaELM

Issue: https://scality.atlassian.net/browse/ZKUI-103

2022-03-08 16:48 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-03-08 16:48 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-103 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.2.0`

* `1.3.0`

* `1.4.0`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-103, or the target
branch of this pull request.

2022-03-08 16:52 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-103-table-alignement` into
`development/1.2`
* [w/1.3/feature/ZKUI-103-table-alignement](https://github.com/scality/zenko-ui/compare/development/1.3...w/1.3/feature/ZKUI-103-table-alignement) will be merged into `development/1.3` 
* [w/1.4/feature/ZKUI-103-table-alignement](https://github.com/scality/zenko-ui/compare/development/1.4...w/1.4/feature/ZKUI-103-table-alignement) will be merged into `development/1.4` 
* [w/1.5/feature/ZKUI-103-table-alignement](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-103-table-alignement) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-03-08 16:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2022-03-08 18:49 UTC, JBWatenbergScality requested changes

2022-03-08 18:49 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +const renderActionButtons = (rowValues: any) => {
You should try not use `any` everywhere but use real typing instead else it defeat the purpose of using typescript :/

2022-03-08 18:49 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +      Cell: (value: any) => renderActionButtons(value.row.original),
Same comment as above here about `any` type usage

2022-03-08 18:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer






The following reviewers are expecting changes from the author, or must review again:

* @jbwatenbergscality

2022-03-09 16:47 UTC, bert-e commented
# History mismatch



Merge commit #c6bacc1a8c508c8547b9e2584ad1fdb77a5a43ff on the integration branch
`w/1.3/feature/ZKUI-103-table-alignement` is merging a branch which is neither the current
branch `feature/ZKUI-103-table-alignement` nor the development branch
`development/1.3`.

It is likely due to a rebase of the branch `feature/ZKUI-103-table-alignement` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-03-11 10:46 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-103 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.2.0`

* `1.3.0`

* `1.4.0`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-103, or the target
branch of this pull request.

2022-03-11 10:47 UTC, AsmaaELM commented
ping

2022-03-11 10:47 UTC, bert-e commented
# History mismatch



Merge commit #c6bacc1a8c508c8547b9e2584ad1fdb77a5a43ff on the integration branch
`w/1.3/feature/ZKUI-103-table-alignement` is merging a branch which is neither the current
branch `feature/ZKUI-103-table-alignement` nor the development branch
`development/1.3`.

It is likely due to a rebase of the branch `feature/ZKUI-103-table-alignement` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-03-15 10:42 UTC, JBWatenbergScality requested changes

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +          {(Rows: any) => (
```suggestion
          {(Rows: JSX.Element) => (
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
>    );
I'm not sure, it would have to be checked but I think currently redux action deleting the location is already handling the error, so I'm afraid that with this implementation 2 modals would be displayed to the user in case of errors. Also I'm not fond of mixing react query together with redux. Either we migrate the whole data fetching to react query either we stick for redux for now. In this specific case I would vote to stick with redux for now as location deletion is pretty complex, it would make sense to do it as part of a planned ticket

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +  const data = useMemo(() => Object.values(locations).map(location => ({...location, asyncMetadataUpdates: true, actions: true})), [locations]);
Maybe we should prefix-sufix these 2 additional keys to avoid any collision with location properties
```suggestion
  const data = useMemo(() => Object.values(locations).map(location => ({...location, _asyncMetadataUpdatesColumn: true, _actionsColumn: true})), [locations]);
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +        accessor: 'asyncMetadataUpdates',
```suggestion
        accessor: '_asyncMetadataUpdatesColumn',
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +      accessor: 'actions',
```suggestion
      accessor: '_actionsColumn',
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/Locations.tsx
> +        >
Please do not use `any` type else it defeat purpose of typing :'(

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +}
I'm not sure to understand the intent of this function reading it's signature. 
 - what is the meaning of this comment `///Amazon S3/` ?
 - why parsing a regexp and limiting the possiblity of getByText ?
 - I think the current factorisation impact readability of the test, abstracting `gridCellOfFirstRow[num]` by `gridCellOfFirstRow, num` doesn't really make sense to me. As a developer I would better understand `expectElementToContainElementByText(elements[1], /TheRegexMatchingMyExpectedText/i)` but I honestly doubt about the added value compared to `expect(getByText(elements[1], /TheRegexMatchingMyExpectedText/i)).toBeInTheDocument()` that is much more explicit to me.

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +}
Same comment as above with regards to this abstraction

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +  it.only('should render Locations component alphabetically sorted', () => {
```suggestion
  it('should render Locations component alphabetically sorted', () => {
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +    //console.log(prettyDOM(buttonOfFirstRow[1]))
```suggestion
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +    const buttonOfSecondtRow = getAllByRole(secondRow, 'button');
```suggestion
    const buttonOfSecondRow = getAllByRole(secondRow, 'button');
```

2022-03-15 10:42 UTC, JBWatenbergScality commented on src/react/backend/location/__tests__/Locations.test.tsx
> +    expectButtonNotDisable(buttonOfFirstRow, 1, 'Delete Location');
I suggest not selecting button by their location in the page but using accessible labels or displayed text, see https://github.com/scality/zenko-ui/pull/271

2022-03-17 15:47 UTC, JBWatenbergScality approved these changes

2022-03-17 15:48 UTC, AsmaaELM commented
/approve

2022-03-17 15:49 UTC, bert-e commented
# History mismatch



Merge commit #c6bacc1a8c508c8547b9e2584ad1fdb77a5a43ff on the integration branch
`w/1.3/feature/ZKUI-103-table-alignement` is merging a branch which is neither the current
branch `feature/ZKUI-103-table-alignement` nor the development branch
`development/1.3`.

It is likely due to a rebase of the branch `feature/ZKUI-103-table-alignement` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2022-03-21 10:18 UTC, AsmaaELM commented
/reset

2022-03-21 10:19 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2022-03-21 10:19 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/1.4/feature/ZKUI-103-table-alignement` with contents from `w/1.3/feature/ZKUI-103-table-alignement`
and `development/1.4`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/1.4/feature/ZKUI-103-table-alignement origin/development/1.4
 $ git merge origin/w/1.3/feature/ZKUI-103-table-alignement
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/1.4/feature/ZKUI-103-table-alignement
```





*The following options are set:* **approve**

2022-03-21 10:19 UTC, bert-e commented
# History mismatch



Merge commit #42242246893d56114ea11dc33de79a3ec45e001f on the integration branch
`w/1.3/feature/ZKUI-103-table-alignement` is merging a branch which is neither the current
branch `feature/ZKUI-103-table-alignement` nor the development branch
`development/1.3`.

It is likely due to a rebase of the branch `feature/ZKUI-103-table-alignement` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2022-03-21 16:23 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-103 contains:


* `1.2.0`

* `1.3.0`

* `1.4.0`

* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.0`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-103, or the target
branch of this pull request.




*The following options are set:* **approve**

2022-03-22 09:07 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-103-table-alignement` into
`development/1.4`
* [w/1.5/feature/ZKUI-103-table-alignement](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-103-table-alignement) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2022-03-22 09:15 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/zenko-ui/commit/c3cd5c8c18bdc000f50dbc5fa4725f205b198d29) did not succeed in branch feature/ZKUI-103-table-alignement.




*The following options are set:* **approve**

2022-03-22 09:51 UTC, bert-e commented
# History mismatch



Merge commit #6b2e48efaec66f9a0814186dc52855bad7c0d767 on the integration branch
`w/1.5/feature/ZKUI-103-table-alignement` is merging a branch which is neither the current
branch `feature/ZKUI-103-table-alignement` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-103-table-alignement` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2022-03-22 10:00 UTC, AsmaaELM commented
/reset

2022-03-22 10:00 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2022-03-22 10:01 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-103-table-alignement` into
`development/1.4`
* [w/1.5/feature/ZKUI-103-table-alignement](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-103-table-alignement) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2022-03-22 10:06 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-03-22 10:06 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue ZKUI-103.

Goodbye asmaaelm.

2022-03-22 10:06 UTC, merged