Testing account users
scality/zenko-ui pull request #271
Opened 2022-03-11 09:31 UTC by AsmaaELM

Issue: https://scality.atlassian.net/browse/ZKUI-69

2022-03-11 09:31 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-03-11 09:31 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-69 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.0`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-69, or the target
branch of this pull request.

2022-03-11 09:34 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-69-users-accounts-testing` into
`development/1.4`
* [w/1.5/feature/ZKUI-69-users-accounts-testing](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-69-users-accounts-testing) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-03-11 09:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2022-03-14 08:42 UTC, bert-e commented
# History mismatch



Merge commit #d3d0dd5de4120f0c7edf402e912d45e86dd96d0a on the integration branch
`w/1.5/feature/ZKUI-69-users-accounts-testing` is merging a branch which is neither the current
branch `feature/ZKUI-69-users-accounts-testing` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-69-users-accounts-testing` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-03-15 09:23 UTC, JBWatenbergScality requested changes

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/AccountUserList.tsx
> +      onError: console.log,
```suggestion
```

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +  prettyDOM,
Please take care of github action warning below:
```
src/react/account/__tests__/AccountUserList.test.tsx#L6
'prettyDOM' is defined but never used
```

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    <QueryClientProvider client={new QueryClient({
The wrapper should likely be moved to a common utils for test file to be mutualised with other tests.
Actually it is already present in `src/react/utils/test.tsx` bellow, so you would just have to factorize this change there and drop this one.

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
>      //TODO test copy arn
This PR address this todo hence it can be removed
```suggestion
```

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    ).toBeInTheDocument();
I think this is likely not testing a specific use case. IIUC here you are checking that when mouse enter the 4th button of the page an element is present somewhere in the screen with the "Copy ARN" text, which is already tested just above. What do you wanted to test here ? A tooltip ? On which button ? Could we localise the button in a better way ? Also if it is a test concerning a tooltip we should localize it more precisely than with "Copy ARN" on the global screen as we saw that just above there is another component with the same text that would match.

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +      eyeButtonOfFirstRow.getElementsByClassName('fas fa-eye')[0].className,
ClassNames are not a reliable selector, please rely on accessible labels instead

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    const eyeButtonOfFirstRow = getAllByRole(firstRow, 'button')[0];
We should better select button by their text as well or accessible labels when we can have several

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    await waitFor(() => screen.getAllByRole('button')[2])
We should better select button by their text as well or accessible labels when we can have several

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    fireEvent.click(screen.getAllByText('Loading users...')[0])
Why clicking on a loading users text ? What do you aim to test here ?

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    ).toBeDefined();
We should better select button by their text as well or accessible labels when we can have several.

Eg. `screen.getByRole('button', {label: 'search'})`

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +    )).toBeInTheDocument();
Same as above We should better select button by their text as well or accessible labels when we can have several.

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/account/__tests__/AccountUserList.test.tsx
> +
```suggestion
```

2022-03-15 09:23 UTC, JBWatenbergScality commented on src/react/utils/test.tsx
> +};
This should be part of locations testing pr

2022-03-15 09:27 UTC, JBWatenbergScality requested changes
I think some tests are missing regarding access keys retrieval and edit of an account

2022-03-16 15:36 UTC, closed without merging

2022-03-17 14:40 UTC, AsmaaELM commented
Testing account users