css polishing
scality/zenko-ui pull request #294
Opened 2022-03-30 06:24 UTC by AsmaaELM

Issue: https://scality.atlassian.net/browse/ZKUI-120

2022-03-30 06:24 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-03-30 06:24 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-120 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.0`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-120, or the target
branch of this pull request.

2022-03-30 16:38 UTC, ChengYanJin requested changes

2022-03-30 16:38 UTC, ChengYanJin commented on src/react/ui-elements/TableKeyValue2.tsx
> +  max-height: calc(100vh - 19rem);
On my side, the Cancel and Save button are still not visible by default...

2022-03-30 17:19 UTC, AsmaaELM commented on src/react/ui-elements/TableKeyValue2.tsx
> +  max-height: calc(100vh - 19rem);
I just tested.  on my branch I get this result:
<img width="1440" alt="Screenshot 2022-03-30 at 19 15 03" src="https://user-images.githubusercontent.com/100131224/160893615-2ece3839-66d7-4b34-86b7-0c42715d9b61.png">
And in development, we have this result : 
<img width="1440" alt="Screenshot 2022-03-30 at 19 15 48" src="https://user-images.githubusercontent.com/100131224/160893754-5c0fc797-1835-4670-9b92-05823eb95355.png">

Or  maybe Yanjin, you're talking about another screen  🤔 ?

2022-03-30 18:46 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-120 contains:


* `1.4.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.1`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-120, or the target
branch of this pull request.

2022-03-30 18:59 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-120 contains:


* `1.4.0`

* `1.4.1`

* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.1`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-120, or the target
branch of this pull request.

2022-03-31 08:13 UTC, AsmaaELM commented on src/react/ui-elements/TableKeyValue2.tsx
> +  max-height: calc(100vh - 19rem);
Here is the expiration edition after css modification:
<img width="1440" alt="Screenshot 2022-03-31 at 10 10 06" src="https://user-images.githubusercontent.com/100131224/161008995-93215250-af1a-4e0e-a646-b26009e12b46.png">

2022-03-31 08:27 UTC, ChengYanJin commented on src/react/ui-elements/TableKeyValue2.tsx
> +  max-height: calc(100vh - 19rem);
Hi @AsmaaELM 
Do you think we can avoid the empty space on the right side of the screen? 
by increasing the width of the workflow table maybe?

2022-03-31 11:30 UTC, ChengYanJin approved these changes

2022-03-31 14:29 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-120-css-polishing-new` into
`development/1.4`
* [w/1.5/feature/ZKUI-120-css-polishing-new](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-120-css-polishing-new) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-03-31 14:29 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @jbwatenbergscality

* @monpote

2022-03-31 16:11 UTC, AsmaaELM commented
/approve

2022-03-31 16:11 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-03-31 16:12 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue ZKUI-120.

Goodbye asmaaelm.

2022-03-31 16:12 UTC, merged