Confirm deletion of object lock
scality/zenko-ui pull request #323
Opened 2022-04-14 10:03 UTC by AsmaaELM

Issue:  https://scality.atlassian.net/browse/ZKUI-134

2022-04-14 10:03 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-04-14 10:03 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-134 contains:


* `1.4.1`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.4`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-134, or the target
branch of this pull request.

2022-04-14 10:06 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-134-Confirm-delete-object-lock` into
`development/1.4`
* [w/1.5/feature/ZKUI-134-Confirm-delete-object-lock](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-134-Confirm-delete-object-lock) will be merged into `development/1.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-04-14 10:06 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @jbwatenbergscality

* @monpote

2022-04-14 10:56 UTC, bert-e commented
# History mismatch



Merge commit #8420ee342c134ab0f6d15a3e51a168d4a30e7106 on the integration branch
`w/1.5/feature/ZKUI-134-Confirm-delete-object-lock` is merging a branch which is neither the current
branch `feature/ZKUI-134-Confirm-delete-object-lock` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-134-Confirm-delete-object-lock` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-04-14 11:42 UTC, AsmaaELM commented
reset

2022-04-19 10:15 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +  color: ${(props) => props.theme.brand.success};
IIRC, the `success` is a deprecated color,  could be replaced by `statusHealthy`.

2022-04-19 10:15 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +        style={{ display: 'inline', width: '55px', marginLeft: '5px', marginRight: '5px', cursor: (confirmed || !toggledFiles.length) ? 'not-allowed': 'default' }}
In general, we use `rem` instead of `px` unit for UI responsiveness. 
Please consider this for all the rest styles below.

2022-04-19 10:15 UTC, ChengYanJin commented on src/react/databrowser/objects/__tests__/ObjectDelete.test.tsx
> -    expect(deleteFilesSpy).toHaveBeenCalledTimes(1);
So how can we make sure the deletion call is made?

2022-04-19 10:15 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-134 contains:


* `1.4.4`

* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.5`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-134, or the target
branch of this pull request.

2022-04-25 15:22 UTC, AsmaaELM commented
ping

2022-04-25 15:22 UTC, bert-e commented
# History mismatch



Merge commit #8420ee342c134ab0f6d15a3e51a168d4a30e7106 on the integration branch
`w/1.5/feature/ZKUI-134-Confirm-delete-object-lock` is merging a branch which is neither the current
branch `feature/ZKUI-134-Confirm-delete-object-lock` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-134-Confirm-delete-object-lock` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-04-26 08:46 UTC, ChengYanJin requested changes
Haven't checked the code yet, discovered the following issues when testing the PR:
- the object protection status in the list is not correct. (Protected, will not be deleted)
- the summary of the deletion should get updated when removing objects from the list.
- if all the objects are not protected, we should hide the Banner, Warning message and Confirmation Input.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

2022-04-27 16:33 UTC, ChengYanJin reviewed
All the comments are targeting a cleaner code. Thanks for considering it.

2022-04-27 16:33 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +        style={{ display: 'inline', width: '3.4375rem', marginLeft: '0.313rem', marginRight: '0.313rem', cursor: (confirmed || !toggledFiles.length) ? 'not-allowed': 'default' }}
I would prefer to extract the style in a styled component

2022-04-27 16:33 UTC, ChengYanJin commented on src/react/databrowser/objects/__tests__/ObjectDelete.test.tsx
> +
Nit: this line of change could be removed

2022-04-27 16:33 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +        Object-Lock retention <Icon style={{ display: 'inline', marginLeft: '0.063rem', marginRight: '0.063rem' }} className="fa fa-lock"></Icon> with governance mode.
I would try to use `spacebox` from core-ui to have a cleaner code.
The purpose of spacebox is to define the margins by using styled-component.

2022-05-02 07:26 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-134 contains:


* `1.4.5`

* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.5.0`


Please check the `Fix Version/s` of ZKUI-134, or the target
branch of this pull request.

2022-05-02 07:35 UTC, AsmaaELM commented
ping

2022-05-02 07:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @jbwatenbergscality

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2022-05-02 07:57 UTC, AsmaaELM commented
@ChengYanJin, Please take a look at my PR and tell me if it's ok for you.

2022-05-02 11:26 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +        }}
```suggestion
      <SpacedBox
        mr={12}
        ml={}
        mt={}
        mb={}
```

For me, the purpose of SpaceBox is to define the margin. It doesn't make sense for me to add another style with margin. You can add `ml`, `mt` and `mb` if you want ;)

2022-05-03 07:43 UTC, ChengYanJin reviewed
Please try to use spacebox as much as possible ;)

2022-05-03 07:43 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +      <div style={{ marginBottom: '1.25rem' }}>
Please use `<SpaceBox/>`

2022-05-03 07:43 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +        <span style={{ marginRight: '0.85rem' }}>Type "confirm" to bypass governance retention:</span>
Please use `<SpaceBox/>`

2022-05-03 07:43 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +  marginRight: 0.313rem;
```js
margin-left: 0.3rem 
margin-right: 0.3rem 
```

or

`margin: 0 0.3rem 0 0.3rem`

2022-05-03 07:43 UTC, ChengYanJin commented on src/react/databrowser/objects/ObjectDelete.tsx
> +      <div style={{ marginBottom: '1.25rem' }}>
Please use <SpaceBox/>

2022-05-03 07:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @monpote

* @jbwatenbergscality





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2022-05-03 08:43 UTC, ChengYanJin approved these changes
LGTM!

2022-05-03 08:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @chengyanjin

* @monpote

* @jbwatenbergscality

2022-05-03 08:44 UTC, AsmaaELM commented
/approve

2022-05-03 08:44 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.5`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/1.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-05-03 08:49 UTC, AsmaaELM commented
/reset

2022-05-03 08:49 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2022-05-03 08:52 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.5`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/1.4`



Please check the status of the associated issue ZKUI-134.

Goodbye asmaaelm.

2022-05-03 08:52 UTC, merged