Policy creation
scality/zenko-ui pull request #362
Opened 2022-06-02 06:58 UTC by AsmaaELM

Issue: https://scality.atlassian.net/browse/ZKUI-173

2022-06-02 06:58 UTC, bert-e commented
# Hello asmaaelm,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2022-06-02 06:58 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-173 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.5.0`


Please check the `Fix Version/s` of ZKUI-173, or the target
branch of this pull request.

2022-06-02 07:02 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-173 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.7`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-173, or the target
branch of this pull request.

2022-06-03 09:33 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-173 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.8`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-173, or the target
branch of this pull request.

2022-06-03 09:47 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-173 contains:


* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.8`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-173, or the target
branch of this pull request.

2022-06-10 13:05 UTC, ChengYanJin requested changes

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +    },
We should handle the error here.
onError: ()=>{}

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +            Policy Name*
```suggestion
            Policy Name
```

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +            tooltipWidth="10.5rem"
We could pass the required prop to the F.Label instead of adding the *
```suggestion
          <F.Label
            htmlFor="policyName"
            tooltipMessages={['The policy name is required']}
            tooltipWidth="10.5rem"
            required
```

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +            ]}
Not sure we really need this tooltip since we have already added the *

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/queries.ts
> +});
```suggestion
export const createPolicyQuery = (accountName: string, policyName: string, policyDocument: string, IAMClient: IAMClient) => ({
  queryKey: ['createPolicy', accountName],
  queryFn: () => IAMClient.putUserPolicy(accountName, policyName, policyDocument),
  enabled: IAMClient !== null,
});
```

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/queries.ts
> +});
```suggestion
export const getListPoliciesQuery = (accountName: string, IAMClient: IAMClient) => ({
  queryKey: ['listPolicies', accountName],
  queryFn: () => IAMClient.getListPolicies(),
  enabled: IAMClient !== null,
});
```

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +    ({ policyName, policyDocument } : Props) => {
would be more straightforward 
```suggestion
    ({ policyName, policyDocument } : {policyName:string, policyDocument:string }) => {
```

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +}
to be removed

2022-06-10 13:05 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +            tooltipMessages={['The policy name is required']}
I believe we can get rid of this tooltipMessages here

2022-06-13 10:11 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue ZKUI-173 contains:


* `1.5.0`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `1.4.9`

* `1.5.0`


Please check the `Fix Version/s` of ZKUI-173, or the target
branch of this pull request.

2022-06-13 13:22 UTC, AsmaaELM commented
ping

2022-06-13 13:22 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/1.5/feature/ZKUI-173-iam-policy-creation` with contents from `feature/ZKUI-173-iam-policy-creation`
and `development/1.5`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/1.5/feature/ZKUI-173-iam-policy-creation origin/development/1.5
 $ git merge origin/feature/ZKUI-173-iam-policy-creation
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/1.5/feature/ZKUI-173-iam-policy-creation
```

2022-06-15 09:01 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-173-iam-policy-creation` into
`development/1.4`
* [w/1.5/feature/ZKUI-173-iam-policy-creation](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-173-iam-policy-creation) will be merged into `development/1.5` 





You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2022-06-15 09:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @monpote

* @chengyanjin

* @jbwatenbergscality





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2022-06-15 19:32 UTC, bert-e commented
# History mismatch



Merge commit #d50cedccc84d018d35d6dcae5af148bde83cd995 on the integration branch
`w/1.5/feature/ZKUI-173-iam-policy-creation` is merging a branch which is neither the current
branch `feature/ZKUI-173-iam-policy-creation` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-173-iam-policy-creation` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-06-16 09:03 UTC, MonPote approved these changes

2022-06-16 09:04 UTC, ChengYanJin approved these changes

2022-06-16 09:04 UTC, ChengYanJin commented on src/react/account/CreateAccountPolicy.tsx
> +        console.log('Error : ', error);
```suggestion
                try {
          dispatch(handleClientError(error));
        } catch (err) {
          dispatch(handleApiError(err as ApiError, 'byModal'));
        }
```

2022-06-16 09:04 UTC, ChengYanJin commented on src/react/account/__tests__/CreateAccountPolicy.test.tsx
> +  it('should disable create button if policy name input and  policy document textarea are empty', async () => {
```suggestion
  it('should disable create button if policy name input and policy document textarea are empty', async () => {
```

2022-06-16 09:22 UTC, AsmaaELM commented
/approve

2022-06-16 09:22 UTC, bert-e commented
# History mismatch



Merge commit #d50cedccc84d018d35d6dcae5af148bde83cd995 on the integration branch
`w/1.5/feature/ZKUI-173-iam-policy-creation` is merging a branch which is neither the current
branch `feature/ZKUI-173-iam-policy-creation` nor the development branch
`development/1.5`.

It is likely due to a rebase of the branch `feature/ZKUI-173-iam-policy-creation` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2022-06-16 09:28 UTC, AsmaaELM commented
/reset

2022-06-16 09:28 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2022-06-16 09:28 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZKUI-173-iam-policy-creation` into
`development/1.4`
* [w/1.5/feature/ZKUI-173-iam-policy-creation](https://github.com/scality/zenko-ui/compare/development/1.5...w/1.5/feature/ZKUI-173-iam-policy-creation) will be merged into `development/1.5` 





You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2022-06-16 09:37 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-06-16 09:37 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.4`

* :heavy_check_mark: `development/1.5`




Please check the status of the associated issue ZKUI-173.

Goodbye asmaaelm.

2022-06-16 09:37 UTC, merged