ZENKO-3055 Add a changelog
scality/zenko-ui pull request #78
Opened 2021-01-08 11:43 UTC by nicolas2bert

2021-01-08 11:43 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/zenko-ui/bert-e/doc/user).





*Status report is not available.*

2021-01-08 11:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @nicolas2bert.

2021-01-11 16:23 UTC, anurag4DSB approved these changes
I did randomly check of these tickets. 
Question: do we need a change log for all projects?

2021-01-11 16:47 UTC, nicolas2bert commented
@anurag4DSB Yes, please check with @terrydervaux.

2021-01-11 17:59 UTC, tmacro approved these changes

2021-01-11 19:22 UTC, miniscruff requested changes

2021-01-11 19:22 UTC, miniscruff commented on CHANGELOG.md
> +Initial release
No need to include the initial release description if we also include what was added, granted I feel the "Added" header is unnecessary here.

2021-01-11 19:22 UTC, miniscruff commented on CHANGELOG.md
> +## [0.1.0] - 2021-01-07
```suggestion
## 0.1.0 - 2021-01-07
```
No need for brackets if there is no link to the tagged release.

2021-01-11 19:22 UTC, miniscruff commented on CHANGELOG.md
> +# Change Log
```suggestion
# Changelog
```
One word

2021-01-11 19:22 UTC, miniscruff commented on CHANGELOG.md
> +### Fixed
```suggestion
```
No need for empty sections

2021-01-11 19:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @nicolas2bert.




The following reviewers are expecting changes from the author, or must review again:

* @miniscruff

2021-01-11 19:40 UTC, miniscruff approved these changes

2021-01-11 19:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @nicolas2bert.

2021-01-12 01:08 UTC, terrydervaux approved these changes
LGTM.

2021-01-12 01:36 UTC, miniscruff commented
@nicolas2bert we might want to update package.json version to match the changelog

2021-01-12 19:06 UTC, nicolas2bert commented
@bert-e approve

2021-01-12 19:06 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-01-12 19:06 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`




Please check the status of the associated issue ZENKO-3055.

Goodbye nicolas2bert.

2021-01-12 19:06 UTC, merged